spring:
  application:
    name: toures-balon-api-gateway
server:
  port: 8085

zuul:
  routes:
     toures-balon-usuario:
        service-id: toures-balon-usuario
        path: /api/tbu/**
---
spring:
  profiles:
    active:
    - dev
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
---
spring:
  profiles: prod
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.17.0.4:8761/eureka
      